### ISSUE TITLE
GUI is gone

### ISSUE THREAD

**Issue by stefan-reich** [profesorfalken/jSensors#14]
The jar file is not executable anymore and I can't even find the GUI class.

**Comment by profesorfalken** [comment]
Hello Stefan, 

You are right. In fact the JAR you have downloaded can only be used as a library.

In order to execute as a standalone program, there is an special executable that contains all the dependencies and the right manifest: https://github.com/profesorfalken/profesorfalken.github.io/raw/master/files/jSensors-2.1.1-jar-with-dependencies.jar

I have updated the README. Thank you for pointing it out.

Best regards
